# -*- coding: latin1 -*-
langs={
"aar":u"afar",
"abk":u"abkhaze",
"ace":u"aceh",
"ach":u"acoli",
"ada":u"adangme",
"ady":u"adyghé",
"afa":u"langues afro-asiatiques",
"afh":u"afrihili",
"afr":u"afrikaans",
"ain":u"aïnou",
"aka":u"akan",
"akk":u"akkadien",
"alb":u"albanais",
"sqi":u"albanais",
"ale":u"aléoute",
"alg":u"langues algonquines",
"alt":u"altai du Sud",
"amh":u"amharique",
"ang":u"anglo-saxon",
"anp":u"angika",
"apa":u"langues apaches",
"ara":u"arabe",
"arc":u"araméen d'empire",
"arg":u"aragonais",
"arm":u"arménien",
"hye":u"arménien",
"arn":u"mapudungun",
"arp":u"arapaho",
"art":u"langues artificielles",
"arw":u"arawak",
"asm":u"assamais",
"ast":u"asturien",
"ath":u"langues athapascanes",
"aus":u"langues australiennes",
"ava":u"avar",
"ave":u"avestique",
"awa":u"awadhi",
"aym":u"aymara",
"aze":u"azéri",
"bad":u"langues banda",
"bai":u"langues bamiléké",
"bak":u"bachkir",
"bal":u"baloutchi",
"bam":u"bambara",
"ban":u"balinais",
"baq":u"basque",
"eus":u"basque",
"bas":u"basa",
"bat":u"langues baltes",
"bej":u"bedja",
"bel":u"biélorusse",
"bem":u"bemba",
"ben":u"bengali",
"ber":u"langues berbères",
"bho":u"bhojpuri",
"bih":u"langues biharis",
"bik":u"bikol",
"bin":u"bini",
"bis":u"bichlamar",
"bla":u"blackfoot",
"bnt":u"langues bantou",
"tib":u"tibétain",
"bod":u"tibétain",
"bos":u"bosniaque",
"bra":u"braj",
"bre":u"breton",
"btk":u"langues batak",
"bua":u"bouriate",
"bug":u"bugi",
"bul":u"bulgare",
"bur":u"birman",
"mya":u"birman",
"byn":u"blin",
"cad":u"caddo",
"cai":u"langues amérindiennes de l'Amérique centrale",
"car":u"karib",
"cat":u"catalan",
"cau":u"langues caucasiennes",
"ceb":u"cebuano",
"cel":u"langues celtiques",
"cze":u"tchèque",
"ces":u"tchèque",
"cha":u"chamorro",
"chb":u"chibcha",
"che":u"tchétchène",
"chg":u"djaghataï",
"chi":u"chinois",
"zho":u"chinois",
"chk":u"chuuk",
"chm":u"mari",
"chn":u"jargon chinook",
"cho":u"choctaw",
"chp":u"chipewyan",
"chr":u"cherokee",
"chu":u"slavon d'église",
"chv":u"tchouvache",
"chy":u"cheyenne",
"cmc":u"langues chames",
"cop":u"copte",
"cor":u"cornique",
"cos":u"corse",
"cpe":u"créoles et pidgins basés sur l'anglais",
"cpf":u"créoles et pidgins basés sur le français",
"cpp":u"créoles et pidgins basés sur le portugais",
"cre":u"cree",
"crh":u"tatar de Crimé",
"crp":u"créoles et pidgins",
"csb":u"kachoube",
"cus":u"langues couchitiques",
"wel":u"gallois",
"cym":u"gallois",
"cze":u"tchèque",
"ces":u"tchèque",
"dak":u"dakota",
"dan":u"danois",
"dar":u"dargwa",
"day":u"langues dayak",
"del":u"delaware",
"den":u"esclave",
"ger":u"allemand",
"deu":u"allemand",
"dgr":u"dogrib",
"din":u"dinka",
"div":u"maldivien",
"doi":u"dogri",
"dra":u"langues dravidiennes",
"dsb":u"bas-sorabe",
"dua":u"douala",
"dum":u"néerlandais moyen",
"dut":u"néerlandais",
"nld":u"néerlandais",
"dyu":u"dioula",
"dzo":u"dzongkha",
"efi":u"efik",
"egy":u"égyptien",
"eka":u"ekajuk",
"gre":u"grec moderne",
"ell":u"grec moderne",
"elx":u"élamite",
"eng":u"anglais",
"enm":u"anglais moyen",
"epo":u"espéranto",
"est":u"estonien",
"baq":u"basque",
"eus":u"basque",
"ewe":u"éwé",
"ewo":u"éwondo",
"fan":u"fang",
"fao":u"féroïen",
"per":u"persan",
"fas":u"persan",
"fat":u"fanti",
"fij":u"fidjien",
"fil":u"filipino",
"fin":u"finnois",
"fiu":u"langues finno-ougriennes",
"fon":u"fon",
"fre":u"français",
"fra":u"français",
"fre":u"français",
"fra":u"français",
"frm":u"français moyen",
"fro":u"français ancien",
"frr":u"frison septentrional",
"frs":u"frison oriental",
"fry":u"frison occidental",
"ful":u"peul",
"fur":u"frioulan",
"gaa":u"ga",
"gay":u"gayo",
"gba":u"gbaya",
"gem":u"langues germaniques",
"geo":u"géorgien",
"kat":u"géorgien",
"ger":u"allemand",
"deu":u"allemand",
"gez":u"guèze",
"gil":u"kiribati",
"gla":u"gaélique",
"gle":u"irlandais",
"glg":u"galicien",
"glv":u"manx",
"gmh":u"moyen haut  allemand",
"goh":u"vieux haut  allemand",
"gon":u"gond",
"gor":u"gorontalo",
"got":u"gothique",
"grb":u"grebo",
"grc":u"grec ancien",
"gre":u"grec moderne",
"ell":u"grec moderne",
"grn":u"guarani",
"gsw":u"suisse alémanique",
"guj":u"goudjrati",
"gwi":u"gwich'in",
"hai":u"haida",
"hat":u"haïtien",
"hau":u"haoussa",
"haw":u"hawaïen",
"heb":u"hébreu",
"her":u"herero",
"hil":u"hiligaynon",
"him":u"langues himachalis",
"hin":u"hindi",
"hit":u"hittite",
"hmn":u"hmong",
"hmo":u"hiri motu",
"hrv":u"croate",
"hsb":u"haut-sorabe",
"hun":u"hongrois",
"hup":u"hupa",
"arm":u"arménien",
"hye":u"arménien",
"iba":u"iban",
"ibo":u"igbo",
"ice":u"islandais",
"isl":u"islandais",
"ido":u"ido",
"iii":u"yi de Sichuan",
"ijo":u"langues ijo",
"iku":u"inuktitut",
"ile":u"interlingue",
"ilo":u"ilocano",
"ina":u"interlingua",
"inc":u"langues indo-aryennes",
"ind":u"indonésien",
"ine":u"langues indo-européennes",
"inh":u"ingouche",
"ipk":u"inupiaq",
"ira":u"langues iraniennes",
"iro":u"langues iroquoises",
"ice":u"islandais",
"isl":u"islandais",
"ita":u"italien",
"jav":u"javanais",
"jbo":u"lojban",
"jpn":u"japonais",
"jpr":u"judéo-persan",
"jrb":u"judéo-arabe",
"kaa":u"karakalpak",
"kab":u"kabyle",
"kac":u"kachin",
"kal":u"groenlandais",
"kam":u"kamba",
"kan":u"kannada",
"kar":u"langues karen",
"kas":u"kashmiri",
"geo":u"géorgien",
"kat":u"géorgien",
"kau":u"kanouri",
"kaw":u"kawi",
"kaz":u"kazakh",
"kbd":u"kabardien",
"kha":u"khasi",
"khi":u"langues khoïsan",
"khm":u"khmer central",
"kho":u"khotanais",
"kik":u"kikuyu",
"kin":u"rwanda",
"kir":u"kirghiz",
"kmb":u"kimbundu",
"kok":u"konkani",
"kom":u"kom",
"kon":u"kongo",
"kor":u"coréen",
"kos":u"kosrae",
"kpe":u"kpellé",
"krc":u"karatchai balkar",
"krl":u"carélien",
"kro":u"langues krou",
"kru":u"kurukh",
"kua":u"kuanyama",
"kum":u"koumyk",
"kur":u"kurde",
"kut":u"kutenai",
"lad":u"judéo-espagnol",
"lah":u"lahnda",
"lam":u"lamba",
"lao":u"lao",
"lat":u"latin",
"lav":u"letton",
"lez":u"lezghien",
"lim":u"limbourgeois",
"lin":u"lingala",
"lit":u"lituanien",
"lol":u"mongo",
"loz":u"lozi",
"ltz":u"luxembourgeois",
"lua":u"luba-lulua",
"lub":u"luba-katanga",
"lug":u"ganda",
"lui":u"luiseno",
"lun":u"lunda",
"luo":u"luo",
"lus":u"lushai",
"mac":u"macédonien",
"mkd":u"macédonien",
"mad":u"madourais",
"mag":u"magahi",
"mah":u"marshall",
"mai":u"maithili",
"mak":u"makassar",
"mal":u"malayalam",
"man":u"mandingue",
"mao":u"maori",
"mri":u"maori",
"map":u"langues austronésiennes",
"mar":u"marathe",
"mas":u"massaï",
"may":u"malais",
"msa":u"malais",
"mdf":u"moksa",
"mdr":u"mandar",
"men":u"mendé",
"mga":u"irlandais moyen",
"mic":u"mi'kmaq",
"min":u"minangkabau",
"mis":u"langues non codées",
"mac":u"macédonien",
"mkd":u"macédonien",
"mkh":u"langues môn-khmer",
"mlg":u"malgache",
"mlt":u"maltais",
"mnc":u"mandchou",
"mni":u"manipuri",
"mno":u"langues manobo",
"moh":u"mohawk",
"mon":u"mongol",
"mos":u"moré",
"mao":u"maori",
"mri":u"maori",
"may":u"malais",
"msa":u"malais",
"mul":u"multilingue",
"mun":u"langues mounda",
"mus":u"muskogee",
"mwl":u"mirandais",
"mwr":u"marvari",
"bur":u"birman",
"mya":u"birman",
"myn":u"langues maya",
"myv":u"erza",
"nah":u"langues nahuatl",
"nai":u"langues nord-amérindiennes",
"nap":u"napolitain",
"nau":u"nauruan",
"nav":u"navaho",
"nbl":u"ndébélé du Sud",
"nde":u"ndébélé du Nord",
"ndo":u"ndonga",
"nds":u"bas allemand",
"nep":u"népalais",
"new":u"nepal bhasa",
"nia":u"nias",
"nic":u"langues nigéro-kordofaniennes",
"niu":u"niué",
"dut":u"néerlandais",
"nld":u"néerlandais",
"nno":u"norvégien nynorsk",
"nob":u"norvégien bokmål",
"nog":u"nogaï",
"non":u"vieux norrois",
"nor":u"norvégien",
"nqo":u"n'ko",
"nso":u"pedi",
"nub":u"langues nubiennes",
"nwc":u"newari classique",
"nya":u"chichewa",
"nym":u"nyamwezi",
"nyn":u"nyankolé",
"nyo":u"nyoro",
"nzi":u"nzema",
"oci":u"occitan",
"oji":u"ojibwa",
"ori":u"oriya",
"orm":u"galla",
"osa":u"osage",
"oss":u"ossète",
"ota":u"turc ottoman",
"oto":u"langues otomi",
"paa":u"langues papoues",
"pag":u"pangasinan",
"pal":u"pahlavi",
"pam":u"pampangan",
"pan":u"pendjabi",
"pap":u"papiamento",
"pau":u"palau",
"peo":u"vieux  perse",
"per":u"persan",
"fas":u"persan",
"phi":u"langues philippines",
"phn":u"phénicien",
"pli":u"pali",
"pol":u"polonais",
"pon":u"pohnpei",
"por":u"portugais",
"pra":u"langues prâkrit",
"pro":u"provençal ancien",
"pus":u"pachto",
"qaa-qtz":u"réservée à l'usage local",
"que":u"quechua",
"raj":u"rajasthani",
"rap":u"rapanui",
"rar":u"rarotonga",
"roa":u"langues romanes",
"roh":u"romanche",
"rom":u"tsigane",
"rum":u"roumain",
"ron":u"roumain",
"rum":u"roumain",
"ron":u"roumain",
"run":u"rundi",
"rup":u"aroumain",
"rus":u"russe",
"sad":u"sandawe",
"sag":u"sango",
"sah":u"iakoute",
"sai":u"langues sud-amérindiennes",
"sal":u"langues salishennes",
"sam":u"samaritain",
"san":u"sanskrit",
"sas":u"sasak",
"sat":u"santal",
"scn":u"sicilien",
"sco":u"écossais",
"sel":u"selkoupe",
"sem":u"langues sémitiques",
"sga":u"irlandais ancien",
"sgn":u"langues des signes",
"shn":u"chan",
"sid":u"sidamo",
"sin":u"singhalais",
"sio":u"langues sioux",
"sit":u"langues sino-tibétaines",
"sla":u"langues slaves",
"slo":u"slovaque",
"slk":u"slovaque",
"slo":u"slovaque",
"slk":u"slovaque",
"slv":u"slovène",
"sma":u"sami du Sud",
"sme":u"sami du Nord",
"smi":u"langues sames",
"smj":u"sami de Lule",
"smn":u"sami d'Inari",
"smo":u"samoan",
"sms":u"sami skolt",
"sna":u"shona",
"snd":u"sindhi",
"snk":u"soninké",
"sog":u"sogdien",
"som":u"somali",
"son":u"langues songhai",
"sot":u"sotho du Sud",
"spa":u"espagnol",
"alb":u"albanais",
"sqi":u"albanais",
"srd":u"sarde",
"srn":u"sranan tongo",
"srp":u"serbe",
"srr":u"sérère",
"ssa":u"langues nilo-sahariennes",
"ssw":u"swati",
"suk":u"sukuma",
"sun":u"soundanais",
"sus":u"soussou",
"sux":u"sumérien",
"swa":u"swahili",
"swe":u"suédois",
"syc":u"syriaque classique",
"syr":u"syriaque",
"tah":u"tahitien",
"tai":u"langues tai",
"tam":u"tamoul",
"tat":u"tatar",
"tel":u"télougou",
"tem":u"temne",
"ter":u"tereno",
"tet":u"tetum",
"tgk":u"tadjik",
"tgl":u"tagalog",
"tha":u"thaï",
"tib":u"tibétain",
"bod":u"tibétain",
"tig":u"tigré",
"tir":u"tigrigna",
"tiv":u"tiv",
"tkl":u"tokelau",
"tlh":u"klingon",
"tli":u"tlingit",
"tmh":u"tamacheq",
"tog":u"tonga",
"ton":u"tongan",
"tpi":u"tok pisin",
"tsi":u"tsimshian",
"tsn":u"tswana",
"tso":u"tsonga",
"tuk":u"turkmène",
"tum":u"tumbuka",
"tup":u"langues tupi",
"tur":u"turc",
"tut":u"langues altaïques",
"tvl":u"tuvalu",
"twi":u"twi",
"tyv":u"touva",
"udm":u"oudmourte",
"uga":u"ougaritique",
"uig":u"ouïgour",
"ukr":u"ukrainien",
"umb":u"umbundu",
"und":u"indéterminée",
"urd":u"ourdou",
"uzb":u"ouszbek",
"vai":u"vaï",
"ven":u"venda",
"vie":u"vietnamien",
"vol":u"volapük",
"vot":u"vote",
"wak":u"langues wakashanes",
"wal":u"wolaitta",
"war":u"waray",
"was":u"washo",
"wel":u"gallois",
"cym":u"gallois",
"wen":u"langues sorabes",
"wln":u"wallon",
"wol":u"wolof",
"xal":u"kalmouk",
"xho":u"xhosa",
"yao":u"yao",
"yap":u"yapois",
"yid":u"yiddish",
"yor":u"yoruba",
"ypk":u"langues yupik",
"zap":u"zapotèque",
"zbl":u"symboles Bliss",
"zen":u"zenaga",
"zgh":u"amazighe standard marocain",
"zha":u"zhuang",
"chi":u"chinois",
"zho":u"chinois",
"znd":u"langues zandé",
"zul":u"zoulou",
"zun":u"zuni",
"zxx":u"pas de contenu linguistique",
"zza":u"zaza",
}
